### ISSUE TITLE
torchvision==0.14.1 is not available in Python>3.10

### ISSUE THREAD

**Issue by stevenvdb** [florisdf/maibi_cv#1]
The requirements file specifies [torchvision==0.14.1](https://github.com/florisdf/maibi_cv/blob/513f88616b3498f34467743a65ef7fed247984a7/requirements.txt#L3), but that version is not available for `Python>3.10` (see https://pypi.org/project/torchvision/). 

If the conda environment has Python 3.11 (which it does by default for me), the installation of the requirements fails with errors like:
```
ERROR: Could not find a version that satisfies the requirement torchvision==0.14.1 
```
Perhaps the easiest way to avoid this, is by fixing the python version in the instructions with:
```
conda create -n maibi_cv python=3.10
```

**Comment by florisdf** [comment]
Hi Steven, thanks for opening this issue! Indeed, the latest Miniconda does not contain Python 3.10 anymore. To fix this, I'll update the Miniconda url and the conda command in the instructions.
